<!--エラー文-->
<% if resource.errors.any? %>
  <div class=“error_explanation”>
    <p class="text-danger"><%= resource.errors.count %>件のエラーが発生しました。</p>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li class="text-danger"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>